### ISSUE TITLE
0.4.1 release?

### ISSUE THREAD

**Issue by eric239** [jhalterman/recurrent#6]
Hi, 
Looks like the examples in README are written for `0.4.1` as they show, among other things, the use of `Listeners`. When do you think `0.4.1` becomes publicly available, e.g. on maven central?
Thanks!

**Comment by jhalterman** [comment]
I think I was still pondering the event listener stuff a bit. I'll need to see where it left off before cutting a a release...

**Comment by talios** [comment]
Any progress on the 0.4.1 release?  Recurrent looks awesome but listeners would be super handy for adding any diagnostic/metrics logging of 'failures'.

**Comment by jhalterman** [comment]
Release will be up within a day. Much apologies for the super slowness. You all are awesome for being so patient.

**Comment by jhalterman** [comment]
0.5.0 is out! It should be in maven central in a few hours.
