### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by cdaringe** [jhalterman/recurrent#7]
hello:

im not sure of your release cycle, but a lot of your great Listener goodness is not in the latest release (0.4.0?).  is the a timeline to publish?

thanks!

chris

**Comment by jhalterman** [comment]
No timeline, but I'd like to get to it soon. I got sidetracked trying to settle on the best way to expose checked exceptions and how those should play with the existing API without being too disruptive...

**Comment by cdaringe** [comment]
no worries.  great little lib.  too bad it wont compile with the android SDK.  the latest android flips out compiling with lambas, even though it suggests to you to use them.  :facepunch: :frowning:

**Comment by cdaringe** [comment]
i ended up just making a jar and bringin it on over

**Comment by jhalterman** [comment]
@cdaringe Are the Android compilation problems just due to the tests? The main source should compile (FWIW) since it doesn't use lambdas - only the tests do.

**Comment by cdaringe** [comment]
@jhalterman, sorry, that was confusing.  all of your stuff is good.  i just can't compile my android-app using lambas.  it eventually results in [this](https://bugs.openjdk.java.net/browse/JDK-8129537).  that's not on you!

**Comment by jhalterman** [comment]
0.5.0 is out! It should be in maven central shortly.

**Comment by cdaringe** [comment]
:game_die: :game_die: :game_die: :game_die: :game_die: 
^^ yahtzee!

**Comment by jhalterman** [comment]
@cdaringe Thanks for your patience on this. If you can help by spreading the word about Recurrent, that would be excellent!
