### ISSUE TITLE
whenSuccess is getting called twice when using AsyncListeners.

### ISSUE THREAD

**Issue by lndbrg** [jhalterman/recurrent#9]
Hi,

I'm running 0.5.0 and want to have a retry listener. From what I understand when calling Recurrent.get in async mode you can only inject AsyncListeners and no Listeners. I want to be able to log on retries and do magic on success. The following code calls whenSuccess twice:

```java
    final AsyncListeners<Object> pullerAsyncListeners = new AsyncListeners<Object>()
        .whenRetryAsync((result, failure, stats) -> {
          log.error("Attempt #{} to start failed: {}",
                    stats.getAttemptCount(),
                    failure.getMessage());
        })

        Recurrent.get(() -> pull(sub), retryPolicy, retryExecutor, pullerAsyncListeners).whenSuccess(p -> log.info("Puller started");
```

Same if I add the whenSuccess block on the AsyncListener and cast it to an AsyncListener again (since whenSuccess returns a Listener).

This code works fine however:
```java
Recurrent.get(() -> pull(sub), retryPolicy, retryExecutor).whenSuccess(p -> log.info("Puller started");
```

**Comment by lndbrg** [comment]
It works if i change whenSuccess to whenSuccessAsync on the RecurrentFuture though.

**Comment by jhalterman** [comment]
You are right that the async `get` API takes an `AsyncListeners` instance, but it extends `Listeners`.

Thanks for filing this. Will have a look in a bit...

**Comment by jhalterman** [comment]
Just pushed 21435d4186fab91929099b5e32274a8301c57f00 which should help with the AsyncListeners API problem you mentioned, and casting.

**Comment by jhalterman** [comment]
This should be good now. You can try the code in master and let me know if it's not. I have one more thing I'd like to get in before cutting a new release, but it should be here shortly...

**Comment by jhalterman** [comment]
0.6.0 is released, and includes this fix.
